name: ğŸ’… Lint
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        name: Eslint - Stylelint
        steps:
            - name: ğŸ‘ Checkout
              uses: actions/checkout@v2

            - name: ğŸ“¥ Install Dependencies
              run: npm install

            - name: ğŸŒ¹ ESLint
              run: npm run lint

            - name: ğŸ’„ StyleLint
              run: npm run stylelint
